---
ID: "26617062-bbcb-4241-99fe-337979e426ad"
Parent: "a7857adc-af24-442c-bd3a-f8ffc97ed384"
Template: "1aaa77bf-78f8-40ae-9930-2a3c6a6ae502"
Path: /sitecore/content/Skate Park/Skate Park/Home/Inventory/DaveO 360
SharedFields:
- ID: "12e9c088-b054-435e-9a9c-c946c11acee3"
  Hint: SKU
  Value: "{26617062-BBCB-4241-99FE-337979E426AD}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{75AD02AF-ED26-4027-BD8F-28EA1BC57F49}"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{F93BE2DB-4626-4185-B2D3-1369863FAC68}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{F6FD9956-4846-4677-BFF2-AAD1E8D6E710}"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7B597223E6-B7EE-4D86-BC89-F7DA3DE8A7E5%7D%7C%7B2C630D25-6B3B-41F2-8365-4D8FEEC06B8F%7D&amp;FieldNames=%7BD10385FE-433B-462E-8856-E76B0C347EAC%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="/headless-main/sxa-product-details/container-1/container-4" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240530T190631Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: DaveO 360
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53e72db3-bd64-4f21-a4f7-63da3e75bc5a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andrew.vieau@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240530T195454Z
    - ID: "ee036325-daf1-4b04-8300-c7b1bd9f575a"
      Hint: Title
      Value: DaveO 360
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{F6FD9956-4846-4677-BFF2-AAD1E8D6E710}"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7B597223E6-B7EE-4D86-BC89-F7DA3DE8A7E5%7D%7C%7B2C630D25-6B3B-41F2-8365-4D8FEEC06B8F%7D&amp;FieldNames=%7BD10385FE-433B-462E-8856-E76B0C347EAC%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="/headless-main/sxa-product-details/container-1/container-4" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240530T204556Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{8E30CE45-DCAE-446A-BCAD-BD740C0F6623}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: DaveO 360
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "92a0005a-964e-4c03-8fe8-d0296135e356"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andrew.vieau@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20240530T204556Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240530T204557Z
    - ID: "ee036325-daf1-4b04-8300-c7b1bd9f575a"
      Hint: Title
      Value: DaveO 360
